Add experimental options
Qiskit/qiskit-ibm-runtime pull request #1067
Opened 2023-09-08 21:58 UTC by jyu00

### Summary

Add some of the experimental options. 

### Details and comments
Fixes #

2023-09-12 21:04 UTC, chriseclectic requested changes
We should the execution options for `samples`,`shots_per_sample`, and `interleave_samples` too

2023-09-12 21:04 UTC, chriseclectic commented on qiskit_ibm_runtime/options/resilience_options.py
> +        default_factory=lambda: ["linear", "multi_exponential"]
Can you avoid default factor if you use a tuple? Either way the default value should be `("exponetial", "linear")` in that order
```suggestion
        default_factory=lambda: ("exponential", "linear")
```

2023-09-12 21:04 UTC, chriseclectic commented on qiskit_ibm_runtime/options/resilience_options.py
> +]
Not sure how you want to handle the `polynomial_degree_k` for 1 <= k <= 7, but you could include the first couple
```suggestion
ZneExtrapolatorType = Literal[
    "exponential",
    "double_exponential",
    "linear",
    "polynomial_degree_1",
    "polynomial_degree_2",
    "polynomial_degree_3",
    "polynomial_degree_4",
]
```

2023-09-14 23:12 UTC, mberna requested changes

2023-09-14 23:12 UTC, mberna commented on qiskit_ibm_runtime/options/resilience_options.py
> +            if resilience_options.get("pec_mitigation"):
One of these two options should be zne_mitigation?
```suggestion
        if resilience_options.get("pec_mitigation"):
            if resilience_options.get("zne_mitigation"):
```

2023-09-15 00:46 UTC, mberna requested changes

2023-09-15 00:46 UTC, mberna commented on qiskit_ibm_runtime/options/options.py
> +        inputs["execution"].update(
are we renaming `run_options` to `execution`?

2023-09-20 02:14 UTC, mberna approved these changes
LGTM!

2023-09-20 22:44 UTC, merged