Disallow unsupported options
Qiskit/qiskit-ibm-runtime pull request #1108
Opened 2023-09-26 16:20 UTC by merav-aharoni

### Summary
Raise an exception if primitives are given unsupported options. We still allow arbitrary options when calling `run()`.

### Details and comments
Fixes #1066.

2023-09-27 08:48 UTC, merav-aharoni commented
I finally decided to simply raise an exception when an illegal option is given in `__init__`. I didn't touch the `kwargs` parameter of `Options`. I am not sure whether this was the intent or not. Feedback is welcome @kt474 , @jyu00 .

2023-09-27 12:43 UTC, jyu00 commented
So Python dataclass already enforces that only documented args and kwargs are allowed. For example, if you do

```
from dataclasses import dataclass

@dataclass
class Foo:
    foo: bool

Foo(bar=1)
```

This would raise an exception `TypeError: __init__() got an unexpected keyword argument 'bar'`.

The `Options` class _bypasses_ this by using the `_flexible` decorator, which then allows arbitrary kwargs. But new code was added to invalidate this bypass ([example](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/options/resilience_options.py#L89-L91)). So basically the situation right now is

1. Python dataclass disallows arbitrary kwargs
2. `_flexible` overwrites (1)
3. Code in options classes overwrite (2)

What #1066 is trying to say is that we should just remove (2) and (3), and let Python handles the enforcement. This is more than just removing the `_flexible` decorator though, since it does more than allowing kwargs.

2023-09-28 18:28 UTC, merav-aharoni commented
> So Python dataclass already enforces that only documented args and kwargs are allowed. For example, if you do
> 
> ```
> from dataclasses import dataclass
> 
> @dataclass
> class Foo:
>     foo: bool
> 
> Foo(bar=1)
> ```
> 
> This would raise an exception `TypeError: __init__() got an unexpected keyword argument 'bar'`.
> 
> The `Options` class _bypasses_ this by using the `_flexible` decorator, which then allows arbitrary kwargs. But new code was added to invalidate this bypass ([example](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/options/resilience_options.py#L89-L91)). So basically the situation right now is
> 
> 1. Python dataclass disallows arbitrary kwargs
> 2. `_flexible` overwrites (1)
> 3. Code in options classes overwrite (2)
> 
> What #1066 is trying to say is that we should just remove (2) and (3), and let Python handles the enforcement. This is more than just removing the `_flexible` decorator though, since it does more than allowing kwargs.

If I understand you correctly, you want the exception to come from the python `dataclass` code, rather than from the `Primitive.__init__`. I made the change. Please let me know what you think.

2023-10-02 12:41 UTC, jyu00 requested changes
> If I understand you correctly, you want the exception to come from the python `dataclass` code, rather than from the `Primitive.__init__`. I made the change. Please let me know what you think.

Correct, since there is no need to write custom code when python does it for you.

2023-10-02 12:41 UTC, jyu00 commented on qiskit_ibm_runtime/options/utils.py
> +                setattr(cls, key, val)
While this accomplishes the desired output, creating a new dataclass (line 98) is unnecessary if we are not allowing arbitrary kwargs. I think it'd be worth understanding what this decorator does to fix the issue properly.

2023-10-25 00:40 UTC, kt474 approved these changes
LGTM

2023-10-26 14:44 UTC, merged