Allow users to specify human-readable service name instead of a CRN
Qiskit/qiskit-ibm-runtime pull request #129
Opened 2022-01-28 13:20 UTC by daka1510

### Summary
With this PR users can choose to set `instance=<service name>` or `instance=<CRN>`. In the first case the CRN value is resolved transparently based on the given name. This requires two additional API calls (i.e. users can opt-in to sacrifice speed for convenience).

### Details and comments
Fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/44

### Follow-Up

- [ ] Make the documentation team aware so that the [documentation](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-access) is updated accordingly

2022-01-31 15:09 UTC, daka1510 commented
@beckykd I think this change also requires updates in the documentation. See summary above and updates in the [tutorial .ipynb files](https://github.com/Qiskit/qiskit-ibm-runtime/pull/129/files) to learn more about the expected updates.

cc: @jyu00

2022-01-31 20:16 UTC, beckykd commented
@daka1510 - Is this only if you're using the Qiskit Python commands, or will it work if you're directly using the cloud API via curl?

2022-01-31 20:36 UTC, rathishcholarajan commented
> @daka1510 - Does this work only if you're using the Qiskit Python commands, or will it work if you're directly using the cloud API via curl?

@beckykd - This feature is available only via Qiskit Python commands.

2022-02-03 14:43 UTC, rathishcholarajan requested changes
Thanks. Left a few minor suggestions... Could you also add a release note? We need to update the release notes section with a few new capabilities (if not all) when compared to using the IBMRuntimeService in qiskit-ibmq-provider so people can understand what's new in this library.

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/utils/utils.py
> +    """Resolves the Custom Resource Name (CRN) for the given cloud account."""
```suggestion
    """Resolves the Cloud Resource Name (CRN) for the given cloud account."""
```

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/accounts/exceptions.py
> +    """Errors raised when the Custom Resource Name (CRN) cannot be resolved for a given service name."""
```suggestion
class CloudResourceNameResolutionError(AccountsError):
    """Errors raised when the Cloud Resource Name (CRN) cannot be resolved for a given service name."""
```

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/accounts/account.py
> +                raise CustomResourceNameResolutionError(
```suggestion
                raise CloudResourceNameResolutionError(
```

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/accounts/account.py
> +            CustomResourceNameResolutionError: if CRN value cannot be resolved.
```suggestion
            CloudResourceNameResolutionError: if CRN value cannot be resolved.
```

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/accounts/account.py
> +from .exceptions import InvalidAccountError, CustomResourceNameResolutionError
```suggestion
from .exceptions import InvalidAccountError, CloudResourceNameResolutionError
```

2022-02-03 14:43 UTC, rathishcholarajan commented on test/test_integration_account.py
> +from qiskit_ibm_runtime.accounts import CustomResourceNameResolutionError
```suggestion
from qiskit_ibm_runtime.accounts import CloudResourceNameResolutionError
```

2022-02-03 14:43 UTC, rathishcholarajan commented on qiskit_ibm_runtime/accounts/account.py
> +    def resolve_cloud_instance_crn(self) -> None:
Can we consider renaming this method? I keep reading it as "Cloud Instance" and keep wondering what it is. May be something like `resolve_crn` or `resolve_service_instance_crn`?

2022-02-03 14:43 UTC, rathishcholarajan commented on test/test_integration_account.py
> +            CustomResourceNameResolutionError
```suggestion
            CloudResourceNameResolutionError
```

2022-02-03 14:43 UTC, rathishcholarajan commented on test/test_integration_account.py
> +        service_instance_name = "-non-existing-service-name-"
Can we write this as a separate test case?

2022-02-03 16:24 UTC, daka1510 commented
Thanks for the feedback, @rathishcholarajan. Addressed your proposals via https://github.com/Qiskit/qiskit-ibm-runtime/pull/129/commits/f815d92b4287e54845bf09dbe46744888d809edd and https://github.com/Qiskit/qiskit-ibm-runtime/pull/129/commits/5805d587b2535e735f40e7d98b1091b8eb55ff9f. Please take a look.

2022-02-03 16:39 UTC, rathishcholarajan commented on releasenotes/notes/resolve-crn-b2cc1c35f5306bea.yaml
> +    You can now set the ``IBM Cloud service name`` as a value for the account ``instance``
```suggestion
    For convenience, you can now set the ``IBM Cloud service name`` as a value for the account ``instance`` 
```

2022-02-03 16:40 UTC, rathishcholarajan commented on releasenotes/notes/resolve-crn-b2cc1c35f5306bea.yaml
> +    :class:`qiskit_ibm_runtime.IBMRuntimeService``` class is slightly higher because the required ``CRN``
```suggestion
    :class:`qiskit_ibm_runtime.IBMRuntimeService` class is slightly higher because the required ``CRN``
```

2022-02-03 16:40 UTC, rathishcholarajan approved these changes
LGTM!

2022-02-03 17:38 UTC, merged