Query programs by search keyword
Qiskit/qiskit-ibm-runtime pull request #19
Opened 2021-11-17 21:21 UTC by kt474

### Summary

Fixes #13 

### Details and comments

There will be merge conflicts with https://github.com/Qiskit/qiskit-ibm-runtime/pull/14

2021-12-01 23:01 UTC, rathishcholarajan requested changes
@kt474 Use the same logic in my comment here https://github.com/Qiskit/qiskit-ibm-runtime/pull/14#issuecomment-984134337

2021-12-06 19:39 UTC, rathishcholarajan requested changes

2021-12-06 19:39 UTC, rathishcholarajan commented on qiskit_ibm_runtime/ibm_runtime_service.py
> +        self._programs_first_call = True
```suggestion
```

2021-12-06 19:39 UTC, rathishcholarajan commented on qiskit_ibm_runtime/ibm_runtime_service.py
> +        self._programs = {}
Same comment as here https://github.com/Qiskit/qiskit-ibm-runtime/pull/14#discussion_r763321347

2022-01-07 06:24 UTC, kt474 commented
Closing and reopening https://github.com/Qiskit/qiskit-ibm-runtime/pull/78 to avoid switching between forks

2022-01-07 06:24 UTC, closed without merging