Add doc for ibm quantum backend spec not optional
Qiskit/qiskit-ibm-runtime pull request #290
Opened 2022-04-21 13:22 UTC by HuangJunye

### Summary

1. Updated getting started guides for sampler and estimator to reflect that backend is required for IBM Quantum while it's optional for IBM Cloud. 
2. Changed the format of program inputs to be closer to the docstring
3. Add link to the respective API reference for Sampler and Estimator.

### Details and comments
Fixes #288

2022-04-21 19:00 UTC, rathishcholarajan commented on docs/tutorials/how-to-getting-started-with-estimator.ipynb
> +    "- **parameters**: a list of parameters for the parameterized circuits. It should be ommitted if the circuits provided are not parameterized.\n",
```suggestion
    "- **parameters**: a list of parameters for the parameterized circuits. It should be omitted if the circuits provided are not parameterized.\n",
```

2022-04-21 19:00 UTC, rathishcholarajan commented on docs/tutorials/how-to-getting-started-with-estimator.ipynb
> +    "- **service**: the `QiskitRuntimeService` instance to run the program on. If not specified, the default saved account for `QiskitRuntimeServie` is initialized.\n",
```suggestion
    "- **service**: the `QiskitRuntimeService` instance to run the program on. If not specified, the default saved account for `QiskitRuntimeService` is initialized.\n",
```

2022-04-21 19:00 UTC, rathishcholarajan commented on docs/tutorials/how-to-getting-started-with-sampler.ipynb
> +    "- **parameters**: a list of parameters for the parameterized circuits. It should be ommitted if the circuits provided are not parameterized.\n",
```suggestion
    "- **parameters**: a list of parameters for the parameterized circuits. It should be omitted if the circuits provided are not parameterized.\n",
```

2022-04-21 19:00 UTC, rathishcholarajan commented on docs/tutorials/how-to-getting-started-with-sampler.ipynb
> +    "- **service**: the `QiskitRuntimeService` instance to run the program on. If not specified, the default saved account for `QiskitRuntimeServie` is initialized.\n",
```suggestion
    "- **service**: the `QiskitRuntimeService` instance to run the program on. If not specified, the default saved account for `QiskitRuntimeService` is initialized.\n",
```

2022-04-21 19:02 UTC, rathishcholarajan requested changes
Looks good except for some typos...

2022-04-22 08:06 UTC, HuangJunye commented
@rathishcholarajan Thanks for spotting the typos! I should install a typo check plugin in my jupyter lab...

2022-04-22 13:00 UTC, rathishcholarajan approved these changes
LGTM!

2022-04-22 13:00 UTC, merged

2022-04-26 10:42 UTC, HuangJunye commented
@rathishcholarajan Seems the doc was not triggered to build, should I start it? Is this the workflow?
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/7631333/165282764-d81083bb-7b81-4edc-b3bd-33d31366408d.png">

2022-04-26 13:42 UTC, rathishcholarajan commented
Yes this is the one, I just ran it this morning. Only thing we need to be careful is to not release docs for any unreleased feature. Right now we haven't merged any features after 0.4, so it's fine for now.