Deprecate circuit_indices and observable_indices and add circuits and observables
Qiskit/qiskit-ibm-runtime pull request #331
Opened 2022-05-19 04:55 UTC by rathishcholarajan

### Summary
Deprecate circuit_indices and observable_indices and add circuits and observables.
circuits and observables can take actual circuits and observables as well as indices.

### Details and comments
Fixes #315

2022-05-26 01:00 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/base_estimator.py
>  # copyright notice, and modified files need to carry a notice indicating
Don't review this file, it was copied from terra.

2022-05-26 01:01 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/base_sampler.py
>  # copyright notice, and modified files need to carry a notice indicating
Don't review this file, it was copied from terra.

2022-05-26 01:01 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/estimator_result.py
Don't review this file, it was copied from terra.

2022-05-26 01:01 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/sampler_result.py
Don't review this file, it was copied from terra.

2022-05-26 01:01 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/utils.py
> +# This code is part of Qiskit.
Don't review this file, it was copied from terra.

2022-05-26 18:33 UTC, rathishcholarajan commented on docs/release_notes.rst
> -    :version: 0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.1.0rc2, 0.1.0rc1
This will be reverted before merging, needed for fork builds to pass. (it's needed here since there is a reno bug)

2022-06-01 13:45 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/base_estimator.py
> +                "The observables passed when calling estimator is not one of the circuits used to "
```suggestion
                "The observables passed when calling estimator is not one of the observables used to "
```

2022-06-01 15:03 UTC, blakejohnson requested changes
This looks good from a correctness perspective. We should update the tutorials to include examples that pass the objects and not just indices.

2022-06-02 17:53 UTC, rathishcholarajan commented
> This looks good from a correctness perspective. We should update the tutorials to include examples that pass the objects and not just indices.

👍 Updated in https://github.com/Qiskit/qiskit-ibm-runtime/pull/331/commits/837368e2381ebaea1897dd7a2e10e51c1aca41ee

2022-06-02 17:58 UTC, blakejohnson approved these changes

2022-06-02 21:50 UTC, merged