Update docs for run_options
Qiskit/qiskit-ibm-runtime pull request #386
Opened 2022-06-20 21:05 UTC by kt474

### Summary

### Details and comments
Fixes #

2022-06-21 14:56 UTC, rathishcholarajan reviewed
@kt474 Have you tried all these options and do all these work?

2022-06-21 18:13 UTC, rathishcholarajan requested changes
This needs to be tested with #240 before merging.

2022-07-27 19:31 UTC, kt474 commented
@rathishcholarajan @renier @kwoane thoughts on updating these docstrings?

I'm also ok with just closing this PR because we are updating the docs [here](https://quantum-computing.ibm.com/services/programs?program=sampler) in ntc-programs PR #210

2022-07-27 20:17 UTC, rathishcholarajan requested changes

2022-07-27 20:17 UTC, rathishcholarajan commented on qiskit_ibm_runtime/qiskit/primitives/base_estimator.py
> +                and use_measure_esp.
These base classes are copied from terra, let's not update these. just sampler.py and estimator.py should be good enough for this PR.

2022-07-27 20:53 UTC, renier commented
> @rathishcholarajan @renier @kwoane thoughts on updating these docstrings?
> 
> I'm also ok with just closing this PR because we are updating the docs [here](https://quantum-computing.ibm.com/services/programs?program=sampler) in ntc-programs PR # 210

I'm fine with updating the docstrings. I just would like to verify that these run_options are actually leveraged in the runtime environment. @rathishcholarajan will probably need your help. This verification can happen as its own issue, though. It doesn't have to block the doc. We can come back and add/update/remove once we investigate run_options more.

2022-07-28 13:48 UTC, renier commented
Let's go ahead without the verification. All the run options are being passed down. Whether they are honored depends on the backend capabilities.

2022-07-28 15:14 UTC, rathishcholarajan approved these changes

2022-07-28 15:34 UTC, merged