Prepare for Cloud authentication support
Qiskit/qiskit-ibm-runtime pull request #39
Opened 2021-11-30 09:45 UTC by daka1510

### Summary

#### Key changes
Extend public interface of `IBMRuntimeService` to prepare for Cloud and Legacy authentication support, i.e.
  - add support for new `auth` and `locator` arguments to class constructor 

#### Minor refactorings
Extended Black to also format setup.py and added a `Code style: black` badge to the README. 

### Details and comments
First step towards https://github.com/Qiskit/qiskit-ibm-runtime/issues/29.

2021-11-30 11:56 UTC, rathishcholarajan requested changes
@daka1510 Could you please resolve merge conflict?

2021-11-30 11:56 UTC, rathishcholarajan commented on qiskit_ibm_runtime/ibm_runtime_service.py
> +                used.
Should we explain a bit here about what is cloud vs what is legacy?

2021-11-30 13:12 UTC, daka1510 commented
@rathishcholarajan resolved merge conflicts and added a comment. Can you take a look again?

2021-11-30 14:03 UTC, rathishcholarajan commented
> @rathishcholarajan resolved merge conflicts and added a comment. Can you take a look again?

@daka1510 Thanks. I don’t see the comment though.

2021-11-30 14:15 UTC, daka1510 commented
Sorry, @rathishcholarajan - forgot to submit the review comment. Done.

2021-11-30 15:35 UTC, rathishcholarajan requested changes
@daka1510 Push tests are failing on your fork, could you please fix those issues? https://github.com/daka1510/qiskit-ibm-runtime/runs/4367753072?check_suite_focus=true#step:5:456

2021-12-01 15:55 UTC, rathishcholarajan approved these changes
@daka1510 Looks good!

2021-12-01 15:55 UTC, merged