Advanced resilience options
Qiskit/qiskit-ibm-runtime pull request #603
Opened 2022-11-06 20:06 UTC by jyu00

### Summary
Add advanced resilience options. 

### Details and comments
Fixes #595

2022-11-07 13:38 UTC, pedrorrivero requested changes
Just one change, everything else LGTM.

Thanks!

2022-11-07 13:38 UTC, pedrorrivero commented on qiskit_ibm_runtime/options/resilience_options.py
> +    "PolynomialExtrapolator",
```suggestion
```

This one is redundant: the type upon which all others are based. It defaults to `LinearExtrapolator` when no extra configuration is given, so should be removed. I updated the documentation accordingly.

2022-11-07 15:38 UTC, pedrorrivero approved these changes
LGTM, thanks!

2022-11-08 15:14 UTC, kt474 approved these changes

2022-11-08 15:15 UTC, merged